In [1]:
import os
import glob
import numpy as np
import pandas as pd
from tqdm import tqdm_notebook as tqdm
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import silhouette_score

In [2]:
cwd = os.getcwd()
data_dir = os.path.join(cwd, 'data')
season = '2017-18'
np.random.seed(2)

In [3]:
df = pd.read_csv(os.path.join(data_dir,'Dataframes','clean', 'df_{}.csv'.format(season)))

In [4]:
columns = ['PTS','3P','AST','DRB','ORB','STL','BLK', 'PF']

In [5]:
df['2P'] = (df['PTS'] - 3*df['3P'] - df['FT'])/2
df['2P'] = df['2P'].astype(int)

In [6]:
columns = ['AST','BLK','DRB','ORB','2P','3P','FT','PF','STL']

In [21]:
data_mean = {'Name':[], 'AST':[], 'BLK':[], 'DRB':[], 'ORB':[], '2P':[], '3P':[], 'FT':[], 'PF':[], 'STL':[]}

for name in tqdm(set(df['Name'])):
    df_cluster = df.loc[df['Name']==name]
    data_mean['Name'].append(name)
    
    for column in columns:
        data_mean[column].append(df_cluster[column].mean())
        
df_mean = pd.DataFrame(data_mean).loc[:, ['Name']+columns]
scaler = MinMaxScaler()
scaler.fit_transform(df_mean.loc[:, columns])
df_mean.head()

HBox(children=(IntProgress(value=0, max=515), HTML(value='')))

,Name,AST,BLK,DRB,ORB,2P,3P,FT,PF,STL
0,Dewayne Dedmon,1.366667,0.766667,6.000000,1.600000,3.100000,0.800000,0.983333,2.516667,0.650000
1,Jusuf Nurkic,1.786667,1.386667,6.493333,2.266667,6.026667,0.000000,2.253333,3.120000,0.813333
2,Treveon Graham,0.797297,0.027027,1.067568,0.567568,0.756757,0.540541,0.554054,1.472973,0.445946
3,Udonis Haslem,0.064935,0.025974,0.077922,0.038961,0.025974,0.012987,0.000000,0.025974,0.000000
4,Kevon Looney,0.573529,0.750000,1.779412,1.088235,1.382353,0.014706,0.617647,1.411765,0.441176

In [23]:
for i in range(df_mean.shape[0]):
    div = sum([df_mean.loc[i, column] for column in columns])
    
    for column in columns:
        if div != 0:
            df_mean.loc[i, column] = (df_mean.loc[i, column]/div)*100
        else:
            df_mean.loc[i, column] = np.nan

In [25]:
df_mean[df_mean.isnull().any(axis=1)]
df_mean = df_mean.dropna().reset_index(drop=True)

In [26]:
X = df_mean.loc[:,columns]

k_means = KMeans(n_clusters=5, verbose=0)
k_means.fit(X)

new_pos = k_means.labels_

In [29]:
df_mean

,Name,AST,BLK,DRB,ORB,2P,3P,FT,PF,STL
0,Dewayne Dedmon,7.685098,4.311153,33.739456,8.997188,17.432052,4.498594,5.529522,14.151828,3.655108
1,Jusuf Nurkic,7.399227,5.742684,26.891220,9.387079,24.958586,0.000000,9.331861,12.921038,3.368305
2,Treveon Graham,12.798265,0.433839,17.136659,9.110629,12.147505,8.676790,8.893709,23.644252,7.158351
3,Udonis Haslem,23.809524,9.523810,28.571429,14.285714,9.523810,4.761905,0.000000,9.523810,0.000000
4,Kevon Looney,7.116788,9.306569,22.080292,13.503650,17.153285,0.182482,7.664234,17.518248,5.474453
5,Royce O'Neale,14.518760,2.446982,30.668842,4.078303,11.419250,5.872757,9.298532,15.823817,5.872757
6,Nikola Jokic,18.970917,2.595078,25.145414,8.322148,16.375839,4.653244,11.275168,8.903803,3.758389
7,Emmanuel Mudiay,25.982256,1.394170,15.842839,3.295311,19.898606,5.956907,12.420786,10.012674,5.196451
8,Shelvin Mack,31.818182,1.038961,17.402597,2.857143,15.584416,5.714286,8.441558,10.519481,6.623377
9,Pau Gasol,15.474553,5.226960,32.324622,8.253095,16.231087,2.819807,10.453920,7.702889,1.513067
10,Jose Calderon,27.553444,0.475059,15.914489,3.087886,11.401425,10.451306,5.700713,19.002375,6.413302
11,Al Jefferson,7.341772,5.822785,26.329114,7.594937,26.329114,0.000000,6.582278,15.949367,4.050633
12,JaKarr Sampson,5.084746,10.734463,24.858757,9.604520,14.689266,2.824859,4.519774,23.163842,4.519774
13,Aaron Harrison,12.307692,3.076923,23.076923,1.538462,7.692308,4.615385,13.846154,24.615385,9.230769
14,Ben Moore,16.666667,0.000000,16.666667,0.000000,0.000000,0.000000,0.000000,66.666667,0.000000
15,Al-Farouq Aminu,7.366483,3.314917,37.016575,8.287293,9.208103,11.233886,5.432781,11.418048,6.721915
16,Thomas Bryant,11.764706,0.000000,29.411765,5.882353,11.764706,5.882353,23.529412,11.764706,0.000000
17,Joe Ingles,26.943005,1.258327,22.797927,1.702443,8.882309,14.655811,4.737232,12.657291,6.365655
18,Tomas Satoransky,28.952991,1.495726,15.918803,6.730769,15.170940,4.700855,8.012821,13.675214,5.341880
19,Evan Fournier,15.507519,1.503759,14.755639,2.161654,22.650376,11.936090,14.097744,12.969925,4.417293
20,Jeff Green,9.381238,3.193613,17.864271,5.688623,22.654691,4.590818,18.762475,13.972056,3.892216
21,Kent Bazemore,18.811881,3.712871,18.399340,2.062706,14.521452,8.910891,13.201320,12.128713,8.250825
22,Jawun Evans,22.222222,1.333333,16.666667,2.000000,16.444444,3.333333,8.444444,21.555556,8.000000
23,Malcolm Brogdon,18.718593,1.633166,16.206030,2.889447,22.487437,7.412060,9.422111,16.080402,5.150754
24,Domantas Sabonis,10.028050,1.963534,26.998597,11.009818,21.318373,0.841515,10.939691,14.446003,2.454418
25,Tyrone Wallace,14.598540,3.163017,18.978102,4.136253,20.194647,2.433090,13.381995,17.274939,5.839416
26,Josh Huestis,5.181347,11.139896,30.829016,10.880829,6.994819,8.290155,1.554404,21.243523,3.886010
27,Emeka Okafor,2.892562,10.330579,27.272727,19.008264,18.595041,0.000000,7.024793,11.983471,2.892562
28,Guerschon Yabusele,13.207547,1.886792,24.528302,14.150943,7.547170,9.433962,7.547170,19.811321,1.886792
29,Marquis Teague,41.666667,0.000000,12.500000,4.166667,12.500000,0.000000,8.333333,12.500000,8.333333
...,...,...,...,...,...,...,...,...,...,...
476,D.J. Wilson,10.344828,3.448276,27.586207,3.448276,20.689655,6.896552,3.448276,17.241379,6.896552
477,Malcolm Delaney,28.646749,1.054482,15.992970,1.581722,11.072056,8.084359,13.005272,14.411248,6.151142
478,Mirza Teletovic,12.987013,1.298701,25.974026,3.896104,5.194805,27.272727,0.000000,18.181818,5.194805
479,Richaun Holmes,10.505837,5.058366,26.848249,10.116732,20.817121,0.778210,6.420233,16.536965,2.918288
480,Andrew Wiggins,9.743252,3.225806,17.116524,4.805793,29.163924,7.044108,12.903226,10.269914,5.727452
481,Michael Beasley,9.400324,3.241491,24.878444,7.293355,29.092382,2.593193,9.481361,11.426256,2.593193
482,Nick Young,6.427221,1.323251,17.769376,3.591682,14.366730,22.495274,9.262760,17.958412,6.805293
483,Ron Baker,25.824176,3.296703,13.736264,2.747253,4.945055,6.043956,10.989011,18.131868,14.285714
484,Bobby Portis,9.531374,1.588562,24.861001,12.311358,22.319301,6.195393,9.451946,9.928515,3.812550
485,Langston Galloway,15.099715,1.424501,20.227920,3.418803,13.390313,19.373219,7.692308,10.826211,8.547009
486,Andre Drummond,8.833785,4.804339,31.538164,14.877954,17.280124,0.000000,9.104998,9.259977,4.300659
487,Dillon Brooks,10.724365,1.505174,17.779868,4.327375,20.790216,8.184384,9.219191,21.354657,6.114770
488,Devin Booker,17.210884,0.952381,14.829932,1.768707,20.952381,10.000000,19.659864,11.428571,3.197279
489,DeMar DeRozan,19.741422,0.944804,12.033814,2.784684,26.752859,4.177026,22.327200,7.160617,4.077573
490,T.J. Warren,6.093190,2.939068,14.910394,8.960573,36.487455,1.433692,13.835125,10.681004,4.659498
491,Derrick Rose,16.831683,1.980198,9.900990,6.435644,33.168317,2.970297,18.811881,7.425743,2.475248
492,Vince Carter,12.753036,5.263158,24.493927,3.441296,10.931174,10.931174,5.060729,18.825911,8.299595
493,Joe Johnson,15.600000,1.400000,29.400000,2.800000,20.200000,7.600000,7.400000,12.000000,3.600000
494,Stephen Curry,20.960108,0.540906,15.212982,2.434077,14.604462,14.334009,18.796484,7.707911,5.409060
495,Marcus Morris,7.971864,1.406800,27.784291,5.041032,18.991794,9.964830,13.599062,11.488863,3.751465
496,Al Horford,21.756225,4.980341,26.867628,6.225426,17.103539,6.159895,5.307995,8.977720,2.621232
497,Dwight Buycks,21.223022,0.719424,10.431655,4.316547,24.100719,5.395683,12.949640,14.028777,6.834532
498,Cheick Diallo,3.603604,4.279279,33.558559,9.009009,20.720721,0.000000,10.810811,15.765766,2.252252
499,Jamal Murray,17.491525,1.762712,14.101695,5.152542,19.796610,10.779661,14.779661,10.847458,5.288136
500,Rudy Gobert,5.214286,8.714286,29.642857,10.928571,18.428571,0.000000,13.928571,10.214286,2.928571
501,Garrett Temple,16.445623,3.580902,17.241379,2.917772,14.588859,11.803714,7.957560,17.904509,7.559682
502,Julyan Stone,26.666667,3.333333,38.333333,0.000000,0.000000,5.000000,1.666667,21.666667,3.333333
503,Okaro White,6.666667,3.333333,26.666667,10.000000,10.000000,13.333333,6.666667,20.000000,3.333333
504,Monte Morris,36.842105,0.000000,10.526316,0.000000,21.052632,0.000000,10.526316,5.263158,15.789474
505,David West,15.034965,8.391608,19.580420,6.993007,24.242424,0.349650,6.759907,13.403263,5.244755

In [28]:
silhouette_score(X, new_pos, sample_size=200)

0.153547701571111

In [ ]:
df['New_Pos'] = new_pos

In [75]:
df['New_Pos'].value_counts()

3    8662
0    7452
2    5593
4    3596
1    2500
Name: New_Pos, dtype: int64

In [77]:
for i in range(5):
    print(df.loc[df['New_Pos']==i, columns].mean(),'\n')

AST    0.069946
BLK    0.042512
DRB    0.130032
ORB    0.069981
2P     0.109066
3P     0.065432
FT     0.052354
PF     0.236536
STL    0.064221
dtype: float64

AST    0.122064
BLK    0.123880
DRB    0.342655
ORB    0.244567
2P     0.310133
3P     0.061320
FT     0.178914
PF     0.481400
STL    0.140286
dtype: float64

AST    0.089326
BLK    0.045557
DRB    0.141004
ORB    0.069939
2P     0.124824
3P     0.108046
FT     0.069296
PF     0.621014
STL    0.102654
dtype: float64

AST    0.016707
BLK    0.008035
DRB    0.026784
ORB    0.012786
2P     0.019906
3P     0.018979
FT     0.011000
PF     0.020396
STL    0.017663
dtype: float64

AST    0.163426
BLK    0.043548
DRB    0.179505
ORB    0.060044
2P     0.184703
3P     0.259066
FT     0.130688
PF     0.249027
STL    0.257389
dtype: float64